version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: 'Asia/Tokyo'
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "13306:3306"

  app:
    image: phyten/template_rails6:alpine-3.0.2-6.1.4.1
    # プロセスが正しく後始末される
    # init: true
    stdin_open: true
    tty: true
    ports:
      - "13000:3000"
    volumes:
      - .:/myapp
      - /myapp/node_modules
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
      - webpacker
  webpacker:
    image: phyten/template_rails6:alpine-3.0.2-6.1.4.1
    stdin_open: true
    tty: true
    volumes:
      - .:/myapp
      - /myapp/node_modules
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bin/webpack-dev-server"

volumes:
  db_data:
